import 'package:flutter/material.dart';

class SemiconductorDiodesScreen extends StatefulWidget {
  const SemiconductorDiodesScreen({super.key});

  @override
  State<SemiconductorDiodesScreen> createState() =>
      _SemiconductorDiodesScreenState();
}

class _SemiconductorDiodesScreenState extends State<SemiconductorDiodesScreen> {
  // Example MCQs (expand up to 50)
  final List<Map<String, dynamic>> questions = [

      {
        "question": "Which of the following is not an electronic device?",
        "options": ["A mobile", "A computer", "A magnifying glass", "A keyboard"],
        "answerIndex": 2
      },
      {
        "question": "Which of the following is not a physical component of an electronic circuit?",
        "options": ["Capacitor", "Inductor", "Diode", "Temperature"],
        "answerIndex": 3
      },
      {
        "question": "Which of the following is not a property of semiconductors used in electronic devices?",
        "options": [
          "They excite electrons",
          "They don’t emit light",
          "They have high thermal conductivity",
          "They have variable electrical conductivity"
        ],
        "answerIndex": 1
      },
      {
        "question": "What is the correct relationship between temperature (T) and mobility (u) of electrons in electronic circuits?",
        "options": ["u ∝ T-3/2", "u ∝ T-1/2", "u ∝ T", "u ∝ T-1"],
        "answerIndex": 0
      },
      {
        "question": "What is the effect of temperature on the recombination rate of electrons in electronic circuits?",
        "options": [
          "Recombination rate increases with temperature",
          "Recombination rate decreases with temperature",
          "Recombination rate is independent of temperature",
          "Recombination doesn’t occur in semiconductors"
        ],
        "answerIndex": 1
      },
      {
        "question": "Which of the following is correct about semiconductors in electronic devices?",
        "options": [
          "Elemental semiconductors have direct band gap",
          "Compound semiconductors have indirect band gap",
          "Extrinsic semiconductors are injected with impurities",
          "Doping is done in Intrinsic semiconductors"
        ],
        "answerIndex": 3
      },
      {
        "question": "Which of the following technique can’t be used for generating electron-hole pairs in electronic devices?",
        "options": [
          "Thermal excitation",
          "Impact ionization",
          "Photo excitation",
          "Impurity injection"
        ],
        "answerIndex": 3
      },
      {
        "question": "Which of the following is not correct about semiconductors in electronic devices?",
        "options": [
          "Electrons are present below Fermi level",
          "Degenerated semiconductors behave like a conductor",
          "Fermi level is independent of temperature and doping",
          "Pentavalent atoms are used in n-type semiconductors"
        ],
        "answerIndex": 2
      },
      {
        "question": "Which of the following equation represents mass action law for semiconductors?",
        "options": ["n × p = ni²", "n × p = ni", "n × p = ni³", "n × p = ni½"],
        "answerIndex": 0
      },
      {
        "question": "Which of the following is correct about Hall Effect in electronic circuits?",
        "options": [
          "Hall voltage is very weak in metals compared to semiconductors",
          "Hall voltage is directly proportional to charge density",
          "Hall voltage is inversely proportional to magnetic field",
          "Intrinsic semiconductor has positive temperature coefficient of Hall constant"
        ],
        "answerIndex": 0
      },
      {
        "question": "Which of the following is not correct about a step-graded junction?",
        "options": [
          "Step-graded junction diodes are slower than normal diodes",
          "They are designed with abrupt junction",
          "They are either p+–n or p–n+ junction",
          "Depletion layer penetrates more into lightly doped region"
        ],
        "answerIndex": 0
      },
      {
        "question": "Which of the following is correct about photo diode?",
        "options": [
          "P-N junction is connected in reverse bias",
          "Electron-hole pairs generated by impurity injection",
          "It is a photovoltaic cell",
          "No external voltage is applied"
        ],
        "answerIndex": 0
      },
      {
        "question": "Which of the following is wrong about solar cell?",
        "options": [
          "Responsivity is directly proportional to wavelength",
          "It produces dark current",
          "It is a photovoltaic cell",
          "No external voltage is applied"
        ],
        "answerIndex": 0
      },
      {
        "question": "What type of semiconductor is used in LED circuits?",
        "options": [
          "Intrinsic semiconductor",
          "Compound semiconductor",
          "Degenerated semiconductor",
          "Compensated semiconductor"
        ],
        "answerIndex": 1
      },
      {
        "question": "Which semiconductor is mostly used to construct electronic circuits?",
        "options": ["Silicon", "Germanium", "Selenium", "Tin"],
        "answerIndex": 0
      },
      {
        "question": "Which of the following is correct about NMOS circuits?",
        "options": [
          "It has N-substrate",
          "For inversion positive voltage is applied to gate",
          "For accumulation positive voltage is applied to gate",
          "NMOS has holes as majority carriers"
        ],
        "answerIndex": 1
      },
      {
        "question": "Which is wrong about threshold voltage (VT) in a MOSFET?",
        "options": [
          "If VT is less, channel forms quickly",
          "VT can be reduced by reducing oxide layer thickness",
          "VT is independent of ion implementation",
          "VT can be reduced by reducing substrate doping"
        ],
        "answerIndex": 2
      },
      {
        "question": "What is the relation between trans-conductance (Gm) and drain-source current (IDS) in NMOS?",
        "options": ["Gm ∝ IDS-3/2", "Gm ∝ IDS-1/2", "Gm ∝ IDS", "Gm ∝ IDS1/2"],
        "answerIndex": 3
      },
      {
        "question": "In which region does BJT act as an amplifier?",
        "options": ["Cut-off", "Saturation", "Active", "Reverse saturation"],
        "answerIndex": 2
      },
      {
        "question": "Which type of semiconductor is used in a Tunnel Diode?",
        "options": [
          "Compound semiconductor",
          "Elemental semiconductor",
          "Degenerated semiconductor",
          "Extrinsic semiconductor"
        ],
        "answerIndex": 2
      },
      {
        "question": "Which is false about Fermi-Dirac distribution function f(E)?",
        "options": [
          "f(E) is the probability of finding an electron in energy level E",
          "When temperature decreases f(E) increases",
          "f(E) doesn’t give number of electrons in a level",
          "f(E) doesn’t give number of energy levels with electrons"
        ],
        "answerIndex": 1
      },
      {
        "question": "A wire of conductivity 5.8×10⁷ mho-m is subjected to 40 mV/m field. What is current density?",
        "options": [
          "2.32×10⁶ A/m²",
          "1.16×10⁶ A/m²",
          "4.64×10⁶ A/m²",
          "4.30×10⁶ A/m²"
        ],
        "answerIndex": 0
      },
      {
        "question": "Mass action law is not valid for which type of semiconductors?",
        "options": ["Compound", "Elemental", "Degenerative", "Compensated"],
        "answerIndex": 2
      },
      {
        "question": "Which is the correct expression of current in intrinsic semiconductor?",
        "options": [
          "ITotal = Ie + Ih",
          "ITotal = Ie – Ih",
          "ITotal = Ie + 2Ih",
          "ITotal = 2Ie + Ih"
        ],
        "answerIndex": 0
      },
      {
        "question": "When an electronic circuit is in equilibrium, which equation is valid?",
        "options": [
          "Jdrift + Jdiffusion = 1",
          "Jdrift + Jdiffusion = 0",
          "Jdrift + Jdiffusion = -1",
          "Jdrift + Jdiffusion = 2"
        ],
        "answerIndex": 1
      },
      {
        "question": "Which of the following is wrong about P-N junction diodes?",
        "options": [
          "They have three modes of operations",
          "They have dynamic resistance at low-frequency AC",
          "They have diffusion capacitance at high-frequency AC",
          "They can act as ON-OFF switches"
        ],
        "answerIndex": 0
      },
      {
        "question": "What is the conductivity of extrinsic semiconductor at 0K?",
        "options": ["Maximum", "Zero", "Can't be determined", "Minimum"],
        "answerIndex": 1
      },
      {
        "question": "What is the conductivity of extrinsic semiconductor at 300K?",
        "options": ["Maximum", "Zero", "Can't be determined", "Minimum"],
        "answerIndex": 0
      },
      {
        "question": "Which effect violates mass action law in degenerative semiconductors?",
        "options": [
          "Thermal effect",
          "Bandgap narrowing effect",
          "Lattice vibration effect",
          "Electronic drift effect"
        ],
        "answerIndex": 1
      },
      {
        "question": "Which diode is used in ultra-high speed switching circuits?",
        "options": [
          "Zener diode",
          "Varactor diode",
          "Tunnel diode",
          "Schottky diode"
        ],
        "answerIndex": 3
      },
      {
        "question": "Which diode is used in adjustable band pass filter circuits?",
        "options": [
          "Zener diode",
          "Varactor diode",
          "Tunnel diode",
          "Schottky diode"
        ],
        "answerIndex": 1
      },
      {
        "question": "Forbidden Energy gap (EG) of a semiconductor depends on which factor?",
        "options": [
          "Interatomic distance",
          "Material constant",
          "Electron affinity",
          "Recombination and Generation"
        ],
        "answerIndex": 0
      },
      {
        "question": "Which of the following is the correct order of turn-off times?",
        "options": [
          "MOSFET < BJT < IGBT < SCR",
          "MOSFET < IGBT < BJT < SCR",
          "SCR < BJT < IGBT < MOSFET",
          "BJT < MOSFET < IGBT < SCR"
        ],
        "answerIndex": 0
      },
      {
        "question": "Which is correct relation for saturation region in NMOS circuits?",
        "options": ["VDS >= VG + VT", "VDS >= VG – VT", "VDS <= VG – VT", "VDS >= VG ± VT"],
        "answerIndex": 1
      },
      {
        "question": "Which type of transistor is preferred in digital and analog circuits?",
        "options": ["BJT", "JFET", "MOSFET", "FET"],
        "answerIndex": 2
      },
      {
        "question": "Which is true about the depletion layer in NMOS circuits?",
        "options": [
          "Inverted charge increases from source to drain",
          "Inverted charge remains constant",
          "Inverted charge decreases from source to drain",
          "Potential decreases from source to drain"
        ],
        "answerIndex": 2
      },
      {
        "question": "Which is true about Zener diode?",
        "options": [
          "It is lightly doped",
          "It is used in voltage regulators",
          "It is used in forward bias",
          "It has avalanche breakdown"
        ],
        "answerIndex": 1
      },
      {
        "question": "In which region does BJT act as an OFF switch?",
        "options": ["Cut-off", "Saturation", "Active", "Reverse saturation"],
        "answerIndex": 0
      },


    {
      "question": "A semiconductor diode is made from?",
      "options": ["Metal", "Semiconductor", "Insulator", "Conductor"],
      "answerIndex": 1
    },
    {
      "question": "The process of adding impurities to a semiconductor is called?",
      "options": ["Biasing", "Rectification", "Doping", "Diffusion"],
      "answerIndex": 2
    },
    {
      "question": "In forward bias, the diode resistance is?",
      "options": ["Very high", "Low", "Infinite", "Zero"],
      "answerIndex": 1
    },
    {
      "question": "In reverse bias, current through a diode is due to?",
      "options": ["Majority carriers", "Minority carriers", "Both", "None"],
      "answerIndex": 1
    },
    {
      "question": "The barrier potential of a silicon diode is about?",
      "options": ["0.3 V", "0.7 V", "1.0 V", "2.0 V"],
      "answerIndex": 1
    },
    {
      "question": "The barrier potential of a germanium diode is about?",
      "options": ["0.1 V", "0.3 V", "0.7 V", "1.0 V"],
      "answerIndex": 1
    },
    {
      "question": "Which diode is used for rectification?",
      "options": ["LED", "Zener", "PN junction diode", "Tunnel diode"],
      "answerIndex": 2
    },
    {
      "question": "A diode allows current to flow in?",
      "options": [
        "Both directions",
        "Only forward direction",
        "Only reverse direction",
        "No direction"
      ],
      "answerIndex": 1
    },
    {
      "question": "The process of converting AC to DC using diodes is?",
      "options": ["Amplification", "Rectification", "Filtering", "Oscillation"],
      "answerIndex": 1
    },
    {
      "question": "Zener diode works in?",
      "options": ["Forward bias", "Reverse bias", "Both", "None"],
      "answerIndex": 1
    },
    {
      "question": "The cut-in voltage of a silicon diode is approximately?",
      "options": ["0.2 V", "0.3 V", "0.7 V", "1.0 V"],
      "answerIndex": 2
    },
    {
      "question": "The cut-in voltage of a germanium diode is approximately?",
      "options": ["0.1 V", "0.2 V", "0.3 V", "0.7 V"],
      "answerIndex": 2
    },
    {
      "question": "When reverse biased, a diode ideally behaves like?",
      "options": ["Open circuit", "Short circuit", "Resistor", "Inductor"],
      "answerIndex": 0
    },
    {
      "question": "When forward biased, a diode ideally behaves like?",
      "options": ["Open circuit", "Short circuit", "Resistor", "Inductor"],
      "answerIndex": 1
    },
    {
      "question": "The reverse saturation current in a diode is due to?",
      "options": ["Majority carriers", "Minority carriers", "Electrons only", "Holes only"],
      "answerIndex": 1
    },
    {
      "question": "Which diode is used as a voltage regulator?",
      "options": ["LED", "Zener diode", "Tunnel diode", "Schottky diode"],
      "answerIndex": 1
    },
    {
      "question": "The most common use of diodes is?",
      "options": ["Amplification", "Rectification", "Oscillation", "Modulation"],
      "answerIndex": 1
    },
    {
      "question": "The current through a diode in forward bias increases?",
      "options": ["Linearly", "Exponentially", "Logarithmically", "Constantly"],
      "answerIndex": 1
    },
    {
      "question": "Reverse breakdown in Zener diode is due to?",
      "options": ["Avalanche effect", "Zener effect", "Both", "None"],
      "answerIndex": 2
    },
    {
      "question": "In half-wave rectifier, efficiency is?",
      "options": ["40.6%", "81.2%", "50%", "25%"],
      "answerIndex": 0
    },
    {
      "question": "In full-wave rectifier, efficiency is?",
      "options": ["40.6%", "81.2%", "50%", "25%"],
      "answerIndex": 1
    },
    {
      "question": "Peak inverse voltage (PIV) of diode is?",
      "options": [
        "Maximum reverse voltage diode can withstand",
        "Maximum forward voltage",
        "Breakdown voltage",
        "Barrier voltage"
      ],
      "answerIndex": 0
    },
    {
      "question": "Schottky diode is made using?",
      "options": ["Metal-Semiconductor junction", "PN junction", "N-N junction", "P-P junction"],
      "answerIndex": 0
    },
    {
      "question": "The forward voltage drop of Schottky diode is?",
      "options": ["0.2–0.3 V", "0.7 V", "1.0 V", "2.0 V"],
      "answerIndex": 0
    },
    {
      "question": "The forward voltage drop of LED is about?",
      "options": ["0.1–0.3 V", "0.7–1.5 V", "2–3 V", "5 V"],
      "answerIndex": 2
    },
    {
      "question": "Light in LED is produced due to?",
      "options": ["Recombination of electrons and holes", "Photon absorption", "Avalanche effect", "Zener breakdown"],
      "answerIndex": 0
    },
    {
      "question": "A photodiode operates in?",
      "options": ["Forward bias", "Reverse bias", "Both", "None"],
      "answerIndex": 1
    },
    {
      "question": "The current in a photodiode is proportional to?",
      "options": ["Voltage applied", "Light intensity", "Temperature", "Barrier potential"],
      "answerIndex": 1
    },
    {
      "question": "Which diode is used in microwave oscillators?",
      "options": ["Zener diode", "Gunn diode", "Tunnel diode", "PIN diode"],
      "answerIndex": 1
    },
    {
      "question": "Tunnel diode exhibits?",
      "options": ["Positive resistance", "Negative resistance", "Zero resistance", "Infinite resistance"],
      "answerIndex": 1
    },
    {
      "question": "Reverse recovery time of a diode is?",
      "options": [
        "Time taken to switch ON",
        "Time taken to switch OFF",
        "Time taken to reach breakdown",
        "None"
      ],
      "answerIndex": 1
    },
    {
      "question": "Which diode is used as a fast switching diode?",
      "options": ["Schottky diode", "Zener diode", "Tunnel diode", "LED"],
      "answerIndex": 0
    },
    {
      "question": "In a PN junction, depletion region consists of?",
      "options": ["Free carriers", "Ions", "Electrons only", "Holes only"],
      "answerIndex": 1
    },
    {
      "question": "The width of depletion layer decreases in?",
      "options": ["Forward bias", "Reverse bias", "Zero bias", "Both"],
      "answerIndex": 0
    },
    {
      "question": "The width of depletion layer increases in?",
      "options": ["Forward bias", "Reverse bias", "Zero bias", "Both"],
      "answerIndex": 1
    },
    {
      "question": "In reverse bias, leakage current is due to?",
      "options": ["Majority carriers", "Minority carriers", "Zener effect", "Avalanche effect"],
      "answerIndex": 1
    },
    {
      "question": "Temperature increases reverse saturation current?",
      "options": ["Decreases", "Increases", "Remains same", "Becomes zero"],
      "answerIndex": 1
    },
    {
      "question": "In a diode, majority carriers flow?",
      "options": ["From N to P", "From P to N", "Both directions", "None"],
      "answerIndex": 0
    },
    {
      "question": "Which diode is widely used in voltage clamping circuits?",
      "options": ["Zener diode", "Schottky diode", "Tunnel diode", "PIN diode"],
      "answerIndex": 0
    },
    {
      "question": "The dynamic resistance of a diode is?",
      "options": ["dV/dI", "dI/dV", "I/V", "V/I"],
      "answerIndex": 0
    },
    {
      "question": "A varactor diode is used in?",
      "options": ["Rectifier", "Voltage regulator", "Tuning circuits", "Amplifier"],
      "answerIndex": 2
    },
    {
      "question": "The symbol of diode has?",
      "options": ["Arrow and bar", "Circle and line", "Triangle only", "Square"],
      "answerIndex": 0
    },
    {
      "question": "Forward current in diode mainly depends on?",
      "options": ["Voltage applied", "Barrier potential", "Temperature", "Material type"],
      "answerIndex": 0
    },
    {
      "question": "Breakdown voltage of diode depends on?",
      "options": ["Doping level", "Temperature", "Barrier potential", "Forward current"],
      "answerIndex": 0
    },
    {
      "question": "Which diode is suitable for high frequency applications?",
      "options": ["Zener", "PIN", "Schottky", "LED"],
      "answerIndex": 2
    },
    {
      "question": "The capacitance of a varactor diode is controlled by?",
      "options": ["Forward current", "Reverse bias voltage", "Temperature", "Light"],
      "answerIndex": 1
    },
    {
      "question": "Zener diode is heavily doped to have?",
      "options": ["Low breakdown voltage", "High forward current", "High capacitance", "Low resistance"],
      "answerIndex": 0
    },
    {
      "question": "The diode equation relates?",
      "options": ["V and I", "R and L", "C and V", "None"],
      "answerIndex": 0
    },
    {
      "question": "The typical reverse saturation current in silicon diode is?",
      "options": ["nA", "µA", "mA", "A"],
      "answerIndex": 0
    },
    {
      "question": "Which diode is used in light detection?",
      "options": ["Zener", "LED", "Photodiode", "Tunnel diode"],
      "answerIndex": 2
    },
  ];


  // Store selected answers for each question
  Map<int, int?> selectedAnswers = {};

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          Text('${questions.length}',style: const TextStyle(color: Colors.white,fontSize: 18),),
          const SizedBox(width: 15,),

        ],
        title: const Text("Semiconductor Diodes",
          style: TextStyle(color: Colors.white,fontSize: 20)),
        backgroundColor: Colors.blue,
        centerTitle: true,
      ),
      body: ListView.builder(
        padding: const EdgeInsets.all(12),
        itemCount: questions.length,
        itemBuilder: (context, qIndex) {
          final question = questions[qIndex];

          return Card(
            color: Colors.grey[100],
            shadowColor: Colors.blue,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(25),
            ),
            margin: const EdgeInsets.symmetric(vertical: 8),
            elevation: 15,
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    "Q${qIndex + 1}. ${question["question"]}",
                    style: const TextStyle(color: Colors.blue,
                        fontSize: 17, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 10),

                  // Options list
                  ...(question["options"] as List<String>)
                      .asMap()
                      .entries
                      .map((entry) {
                    int optIndex = entry.key;
                    String option = entry.value;

                    bool isSelected = selectedAnswers[qIndex] == optIndex;
                    bool isCorrectOption = optIndex == question["answerIndex"];
                    bool showCorrect = isCorrectOption && isSelected;
                    bool showWrong = isSelected && !isCorrectOption;

                    return Container(
                      margin: const EdgeInsets.symmetric(vertical: 4),
                      child: ListTile(
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8),
                          side: BorderSide(
                            color: showCorrect
                                ? Colors.green
                                : showWrong
                                ? Colors.red
                                : Colors.grey.shade300,
                          ),
                        ),
                        tileColor: showCorrect
                            ? Colors.green.shade100
                            : showWrong
                            ? Colors.red.shade100
                            : null,
                        title: Text(option),
                        trailing: showCorrect
                            ? const Icon(Icons.check_circle, color: Colors.green)
                            : showWrong
                            ? const Icon(Icons.cancel, color: Colors.red)
                            : null,
                        onTap: () {
                          setState(() {
                            // Only allow selecting until the correct is chosen
                            if (selectedAnswers[qIndex] !=
                                question["answerIndex"]) {
                              selectedAnswers[qIndex] = optIndex;
                            }
                          });
                        },
                      ),
                    );
                  }),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
